title: Gibson Lab
tagline: Harvard Medical School
author:
  name: Travis Gibson
  email: tegibson@bwh.harvard.edu
description: The Gibson Lab leverages tools from machine learning and control theory to study biological systems. PI - Travis Gibson.
logo: /image/gibson_lab_logo_bw_outlined_cropped_html.svg
url: https://gibsonlab.io


show_excerpts: false # set to true to show excerpts on the homepage

google_analytics: G-T72G0671VR

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"
  skin: classic
  # generate social links in footer
  social_links:
    # twitter: jekyllrb
    # github:  jekyll
    # devto: jekyll
    # dribbble: jekyll
    # facebook: jekyll
    # flickr:   jekyll
    # instagram: jekyll
    # linkedin: jekyll
    # pinterest: jekyll
    # youtube: jekyll
    # youtube_channel: UC8CXR0-3I70i1tfPg1PAE1g
    # youtube_channel_name: CloudCannon
    # telegram: jekyll
    # googleplus: +jekyll
    # microdotblog: jekyll
    # keybase: jekyll

    # Mastodon instances
    # mastodon:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

    # GitLab instances
    # gitlab:
    # - username: jekyll
    #   instance: example.com
    # - username: jekyll2
    #   instance: example.com

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
header_pages:
# - index.md
 - about.md
 - people.md
 - positions.md
 - publications.md


social:
  name: Gibson Lab
  links:
    - https://twitter.com/GibsonNews
    - https://github.com/GibsonLab


# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
